---
# handlers file for kafka
- name: restart kafka
  systemd:
    name: kafka
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: start kafka
  systemd:
    name: kafka
    state: started
    enabled: yes
    daemon_reload: yes
