---
# defaults file for kafka
xfs_mount_opts: defaults,nobarrier,noatime
apache_mirror: http://apache.osuosl.org
kafka_version: 0.11.0.2
kafka_download_url: "{{ apache_mirror }}/kafka/{{ kafka_version }}/kafka_2.12-{{ kafka_version }}.tgz"
kafka_install_dir: /usr/local/kafka_2.12-{{ kafka_version }}
kafka_data_dir: /var/lib/kafka/logs
kafka_log_dir: /var/log/kafka
kafka_user: root
kafka_group: root
kafka_heap_opts: -Xms32g -Xmx32g
kafka_num_partitions: 3
kafka_num_replicas: 2
